name: chat-backend-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login ghcr.io -u ${username} -p ${password}
    - name: Build image
      run: docker build . -t ghcr.io/memelabs/chat/chat-backend:latest
    - name: Publish image
      run: docker push ghcr.io/memelabs/chat/chat-backend:latest
    - name: ssh-deploy for chat
      uses: appleboy/ssh-action@122f35dca5c7a216463c504741deb0de5b301953
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          ./hooks/chat-backend.sh
